language: r
sudo: required
cache: packages
r:
  - devel

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4 # give xvfb some time to start
  
r_packages:
  - devtools

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false
